### ISSUE TITLE
MacAdmins Slack Email Domain Registration Restriction.

### ISSUE THREAD

**Issue by lczaplicki16** [macadminsdotorg/slack-assets#10]
Can't sign up for MacAdmins Slack due to email domain restriction

<img width="612" alt="image" src="https://user-images.githubusercontent.com/58995105/175074370-ba419b11-2ebf-4e8b-9bb4-0e1aec04ca87.png">

**Comment by quovadimus** [comment]
Joining the MacAdmins slack is done with the JOIN NOW button on https://www.macadmins.org/.  This option may have appeared temporarily while there was an issue with the link, but it is resolved.
